export const colors ={
    COLOR_PRIMARY: "#f96163",
    COLOR_LIGHT: "#fff",
    COLOR_DARK: "#000",
    COLOR_DARK_ALT: "#262626",
};

// Data for categories filter

export const categories = [
    {
        id:"01",
        category:"Breakfast",
    },
    {
        id:"02",
        category:"Lunch",
    },
    {
        id:"03",
        category:"Dinner",
    },
    {
        id:"04",
        category:"Asian",
    },
    {
        id:"05",
        category:"Italian",
    },
    {
        id:"06",
        category:"Desserts",
    },
    {
        id:"07",
        category:"Vegetarian",
    },
    {
        id:"08",
        category:"Seafood",
    },
];

export const recipeList = [
    {
      id: "01",
      name: "Tuna Tartare",
      image: require("../assets/images/TunaTartare.png"),
      rating: "4.2",
      //ingredients: ["Fresh Tuna", "Lime Juice", "Red wine", "Avacardo"],
      time: "40 mins",
      difficulty: "Medium",
      calories: "420 cal",
        color:"#f39c12",
        ingredients:["1 lb Ahi Tuna fresh, sushi grade tuna fillet",
            "Ahi Tuna Marinade",
        "1 teaspoon ginger grated",
        "1 teaspoon garlic grated",
        "11/2 Tablespoon soy sauce",
        "1 teaspoon lime juice",
        "2 tablespoons sweet chilli sauce",
        "2 teaspoons cilantro minced",
        "2 tablespoons scallions minced",
        "1 tablespoon sesame oil",
        "1 teaspoon Sriracha sauce optional",
        "3 tablespoons sesame seeds mixed white and black sesame",],
        description:"If you love tuna, then you're going to love this recipe for Tuna tartare. This dish is made with fresh ahi tuna and a delicious Asian sauce that will tantalize your taste buds. Layered with flavored chunks of avocado, this tuna recipe & video ate a MUST try! ",
        steps:[
            "Make sure you pat the tuna fillet dry using a paper towel.",
            "Use a sharp knife to dice the tuna into 1 inch dices",
            "Try to keep the size unifrom as much as possible and avoid making too small of chunk, as this will cure quickly in the marinade.",
            "Now mix all the marinade ingredients in a bowl.",
            "Add in the tuna and mix well.",
            "Repeat with the avocado mixture, mix everything together in a separate bowl.",
            "Now to assemble the tartare, take a mold or ramekin or bowl.",
            "Oil the indies of the bowl or mold using a brush.",
            "Start by placing the avocado at the bottom layer (if flipping a bowl then start by the tua layer). and press it down.",
            "Now add in the tuna layer and press it down.",
            "Carefully remove the mold and you'll have tuna tartare stack.",
            "Serve with some pita chips or cucumber rounds",
            "Enjoy"
        ],
    },
    {
        id: "02",
        name: "Lasagna",
        image: require("../assets/images/Lasgna.png"),
        rating: "3.6",
        //ingredients: ["Lasagna Noodles", "Ground beef", "Ricotta Cheese", "Tomato Sauce"],
        time: "40 mins",
        difficulty: "Medium",
        calories: "420 cal",
        color:"#00ffff",
        ingredients:["1 lb Ahi Tuna fresh, sushi grade tuna fillet",
            "Ahi Tuna Marinade",
            "1 teaspoon ginger grated",
            "1 teaspoon garlic grated",
            "11/2 Tablespoon soy sauce",
            "1 teaspoon lime juice",
            "2 tablespoons sweet chilli sauce",
            "2 teaspoons cilantro minced",
            "2 tablespoons scallions minced",
            "1 tablespoon sesame oil",
            "1 teaspoon Sriracha sauce optional",
            "3 tablespoons sesame seeds mixed white and black sesame",],
        description:"If you love tuna, then you're going to love this recipe for Tuna tartare. This dish is made with fresh ahi tuna and a delicious Asian sauce that will tantalize your taste buds. Layered with flavored chunks of avocado, this tuna recipe & video ate a MUST try! ",
        steps:[
            "Make sure you pat the tuna fillet dry using a paper towel.",
            "Use a sharp knife to dice the tuna into 1 inch dices",
            "Try to keep the size unifrom as much as possible and avoid making too small of chunk, as this will cure quickly in the marinade.",
            "Now mix all the marinade ingredients in a bowl.",
            "Add in the tuna and mix well.",
            "Repeat with the avocado mixture, mix everything together in a separate bowl.",
            "Now to assemble the tartare, take a mold or ramekin or bowl.",
            "Oil the indies of the bowl or mold using a brush.",
            "Start by placing the avocado at the bottom layer (if flipping a bowl then start by the tua layer). and press it down.",
            "Now add in the tuna layer and press it down.",
            "Carefully remove the mold and you'll have tuna tartare stack.",
            "Serve with some pita chips or cucumber rounds",
            "Enjoy"
        ],
    },
    {
        id: "03",
        name: "Hot Dog",
        image: require("../assets/images/HotDogN.png"),
        rating: "4.6",
        //ingredients: ["Hot Dog Buns", "Ground beef", "Ricotta Cheese", "Tomato Sauce"],
        time: "40 mins",
        difficulty: "Medium",
        calories: "420 cal",
        color:"#8a2be2",
        ingredients:["1 lb Ahi Tuna fresh, sushi grade tuna fillet",
            "Ahi Tuna Marinade",
            "1 teaspoon ginger grated",
            "1 teaspoon garlic grated",
            "11/2 Tablespoon soy sauce",
            "1 teaspoon lime juice",
            "2 tablespoons sweet chilli sauce",
            "2 teaspoons cilantro minced",
            "2 tablespoons scallions minced",
            "1 tablespoon sesame oil",
            "1 teaspoon Sriracha sauce optional",
            "3 tablespoons sesame seeds mixed white and black sesame",],
        description:"If you love tuna, then you're going to love this recipe for Tuna tartare. This dish is made with fresh ahi tuna and a delicious Asian sauce that will tantalize your taste buds. Layered with flavored chunks of avocado, this tuna recipe & video ate a MUST try! ",
        steps:[
            "Make sure you pat the tuna fillet dry using a paper towel.",
            "Use a sharp knife to dice the tuna into 1 inch dices",
            "Try to keep the size unifrom as much as possible and avoid making too small of chunk, as this will cure quickly in the marinade.",
            "Now mix all the marinade ingredients in a bowl.",
            "Add in the tuna and mix well.",
            "Repeat with the avocado mixture, mix everything together in a separate bowl.",
            "Now to assemble the tartare, take a mold or ramekin or bowl.",
            "Oil the indies of the bowl or mold using a brush.",
            "Start by placing the avocado at the bottom layer (if flipping a bowl then start by the tua layer). and press it down.",
            "Now add in the tuna layer and press it down.",
            "Carefully remove the mold and you'll have tuna tartare stack.",
            "Serve with some pita chips or cucumber rounds",
            "Enjoy"
        ],
    },
    {
        id: "04",
        name: "Manchurian",
        image: require("../assets/images/Manchurian.jpg"),
        rating: "3.6",
        //ingredients: ["Cauliflower", "Soy Sauce"],
        time: "30 mins",
        difficulty: "Easy",
        calories: "420 cal",
        color:"#a52a2a",
        ingredients:["1 lb Ahi Tuna fresh, sushi grade tuna fillet",
            "Ahi Tuna Marinade",
            "1 teaspoon ginger grated",
            "1 teaspoon garlic grated",
            "11/2 Tablespoon soy sauce",
            "1 teaspoon lime juice",
            "2 tablespoons sweet chilli sauce",
            "2 teaspoons cilantro minced",
            "2 tablespoons scallions minced",
            "1 tablespoon sesame oil",
            "1 teaspoon Sriracha sauce optional",
            "3 tablespoons sesame seeds mixed white and black sesame",],
        description:"If you love tuna, then you're going to love this recipe for Tuna tartare. This dish is made with fresh ahi tuna and a delicious Asian sauce that will tantalize your taste buds. Layered with flavored chunks of avocado, this tuna recipe & video ate a MUST try! ",
        steps:[
            "Make sure you pat the tuna fillet dry using a paper towel.",
            "Use a sharp knife to dice the tuna into 1 inch dices",
            "Try to keep the size unifrom as much as possible and avoid making too small of chunk, as this will cure quickly in the marinade.",
            "Now mix all the marinade ingredients in a bowl.",
            "Add in the tuna and mix well.",
            "Repeat with the avocado mixture, mix everything together in a separate bowl.",
            "Now to assemble the tartare, take a mold or ramekin or bowl.",
            "Oil the indies of the bowl or mold using a brush.",
            "Start by placing the avocado at the bottom layer (if flipping a bowl then start by the tua layer). and press it down.",
            "Now add in the tuna layer and press it down.",
            "Carefully remove the mold and you'll have tuna tartare stack.",
            "Serve with some pita chips or cucumber rounds",
            "Enjoy"
        ],
    },
    {
        id: "05",
        name: "Manchurian",
        image: require("../assets/images/Manchurian.jpg"),
        rating: "3.6",
        ingredients: ["Cauliflower", "Soy Sauce"],
        time: "30 mins",
        difficulty: "Easy",
        calories: "420 cal",
        color:"#ff7f50",
    },
    {
        id: "06",
        name: "Manchurian",
        image: require("../assets/images/Manchurian.jpg"),
        rating: "3.6",
        ingredients: ["Cauliflower", "Soy Sauce"],
        time: "30 mins",
        difficulty: "Easy",
        calories: "420 cal",
        color:"#228b22",
    },
    {
        id: "07",
        name: "Manchurian",
        image: require("../assets/images/Manchurian.jpg"),
        rating: "3.6",
        ingredients: ["Cauliflower", "Soy Sauce"],
        time: "30 mins",
        difficulty: "Easy",
        calories: "420 cal",
        color:"#ff00ff",
    },
    {
        id: "08",
        name: "Manchurian",
        image: require("../assets/images/Manchurian.jpg"),
        rating: "3.6",
        ingredients: ["Cauliflower", "Soy Sauce"],
        time: "30 mins",
        difficulty: "Easy",
        calories: "420 cal",
        color:"#7cfc00",
    },


];